# Список логотипов команд
logos_khl = {
    "авангард": "Авангард.png",
    "ак барс": "Ак Барс.png",
    "акбарс": "Ак Барс.png",
    "металлург": "Металлург.png",
    "металург": "Металлург.png",
    "амур": "Амур.png",
    "барыс": "Барыс.png",
    "адмирал": "Адмирал.png",
    "локомотив": "Локомотив.png",
    "сочи": "Сочи.png",
    "трактор": "Трактор.png",
    "торпедо": "Торпедо.png",
    "салават": "Салават Юлаев.png",
    "сибирь": "Сибирь.png",
    "спартак": "Спартак.png",
    "цска": "ЦСКА.png",
    "ска": "СКА.png",
    "минск": "Динамо Минск.png",
    "динамо минск": "Динамо Минск.png",
    "витязь": "Витязь.png",
    "кунь лунь": "Кунь Лунь.png",
    "куньлунь": "Кунь Лунь.png",
    "автомобилист": "Автомобилист.png",
    "лада": "Лада.png",
    "северсталь": "Северсталь.png",
    "нефтехимик": "Нефтехимик.png",
    "динамо": "Динамо Москва.png",
}

# logos_khl = {
#     "авангард": r"Z:\IT_files\PycharmProjects\Pupkov_TG_imag\files_for_pict\logo_khl\Авангард.png",
#     "ак барс": r"Z:\IT_files\PycharmProjects\Pupkov_TG_imag\files_for_pict\logo_khl\Ак Барс.png",
#     "акбарс": r"Z:\IT_files\PycharmProjects\Pupkov_TG_imag\files_for_pict\logo_khl\Ак Барс.png",
#     "металлург": r"Z:\IT_files\PycharmProjects\Pupkov_TG_imag\files_for_pict\logo_khl\Металлург.png",
#     "металург": r"Z:\IT_files\PycharmProjects\Pupkov_TG_imag\files_for_pict\logo_khl\Металлург.png",
#     "амур": r"Z:\IT_files\PycharmProjects\Pupkov_TG_imag\files_for_pict\logo_khl\Амур.png",
#     "барыс": r"Z:\IT_files\PycharmProjects\Pupkov_TG_imag\files_for_pict\logo_khl\Барыс.png",
#     "адмирал": r"Z:\IT_files\PycharmProjects\Pupkov_TG_imag\files_for_pict\logo_khl\Адмирал.png",
#     "локомотив": r"Z:\IT_files\PycharmProjects\Pupkov_TG_imag\files_for_pict\logo_khl\Локомотив.png",
#     "сочи": r"Z:\IT_files\PycharmProjects\Pupkov_TG_imag\files_for_pict\logo_khl\Сочи.png",
#     "трактор": r"Z:\IT_files\PycharmProjects\Pupkov_TG_imag\files_for_pict\logo_khl\Трактор.png",
#     "торпедо": r"Z:\IT_files\PycharmProjects\Pupkov_TG_imag\files_for_pict\logo_khl\Торпедо.png",
#     "салават": r"Z:\IT_files\PycharmProjects\Pupkov_TG_imag\files_for_pict\logo_khl\Салават Юлаев.png",
#     "сибирь": r"Z:\IT_files\PycharmProjects\Pupkov_TG_imag\files_for_pict\logo_khl\Сибирь.png",
#     "спартак": r"Z:\IT_files\PycharmProjects\Pupkov_TG_imag\files_for_pict\logo_khl\Спартак.png",
#     "цска": r"Z:\IT_files\PycharmProjects\Pupkov_TG_imag\files_for_pict\logo_khl\ЦСКА.png",
#     "ска": r"Z:\IT_files\PycharmProjects\Pupkov_TG_imag\files_for_pict\logo_khl\СКА.png",
#     "минск": r"Z:\IT_files\PycharmProjects\Pupkov_TG_imag\files_for_pict\logo_khl\Динамо Минск.png",
#     "динамо минск": r"Z:\IT_files\PycharmProjects\Pupkov_TG_imag\files_for_pict\logo_khl\Динамо Минск.png",
#     "витязь": r"Z:\IT_files\PycharmProjects\Pupkov_TG_imag\files_for_pict\logo_khl\Витязь.png",
#     "кунь лунь": r"Z:\IT_files\PycharmProjects\Pupkov_TG_imag\files_for_pict\logo_khl\Кунь Лунь.png",
#     "куньлунь": r"Z:\IT_files\PycharmProjects\Pupkov_TG_imag\files_for_pict\logo_khl\Кунь Лунь.png",
#     "автомобилист": r"Z:\IT_files\PycharmProjects\Pupkov_TG_imag\files_for_pict\logo_khl\Автомобилист.png",
#     "лада": r"Z:\IT_files\PycharmProjects\Pupkov_TG_imag\files_for_pict\logo_khl\Лада.png",
#     "северсталь": r"Z:\IT_files\PycharmProjects\Pupkov_TG_imag\files_for_pict\logo_khl\Северсталь.png",
#     "нефтехимик": r"Z:\IT_files\PycharmProjects\Pupkov_TG_imag\files_for_pict\logo_khl\Нефтехимик.png",
#     "динамо": r"Z:\IT_files\PycharmProjects\Pupkov_TG_imag\files_for_pict\logo_khl\Динамо Москва.png"
# }

# logos_nhl = {
#     "анахайм": r"Z:\Documents\Hockey History\Telegram-канал\Графика\Итоги игрового дня КХЛ\Материал\Лого НХЛ\Лого - НХЛ - Фон\Анахайм.png",
#     "аризона": r"Z:\Documents\Hockey History\Telegram-канал\Графика\Итоги игрового дня КХЛ\Материал\Лого НХЛ\Лого - НХЛ - Фон\Аризона.png",
#     "баффоло": r"Z:\Documents\Hockey History\Telegram-канал\Графика\Итоги игрового дня КХЛ\Материал\Лого НХЛ\Лого - НХЛ - Фон\Баффоло.png",
#     "бафоло": r"Z:\Documents\Hockey History\Telegram-канал\Графика\Итоги игрового дня КХЛ\Материал\Лого НХЛ\Лого - НХЛ - Фон\Баффоло.png",
#     "баффало": r"Z:\Documents\Hockey History\Telegram-канал\Графика\Итоги игрового дня КХЛ\Материал\Лого НХЛ\Лого - НХЛ - Фон\Баффоло.png",
#     "бафало": r"Z:\Documents\Hockey History\Telegram-канал\Графика\Итоги игрового дня КХЛ\Материал\Лого НХЛ\Лого - НХЛ - Фон\Баффоло.png",
#     "бостон": r"Z:\Documents\Hockey History\Telegram-канал\Графика\Итоги игрового дня КХЛ\Материал\Лого НХЛ\Лого - НХЛ - Фон\Бостон.png",
#     "вашингтон": r"Z:\Documents\Hockey History\Telegram-канал\Графика\Итоги игрового дня КХЛ\Материал\Лого НХЛ\Лого - НХЛ - Фон\Вашингтон.png",
#     "виннипег": r"Z:\Documents\Hockey History\Telegram-канал\Графика\Итоги игрового дня КХЛ\Материал\Лого НХЛ\Лого - НХЛ - Фон\Винипег.png",
#     "винипег": r"Z:\Documents\Hockey History\Telegram-канал\Графика\Итоги игрового дня КХЛ\Материал\Лого НХЛ\Лого - НХЛ - Фон\Винипег.png",
#     "ванкувер": r"Z:\Documents\Hockey History\Telegram-канал\Графика\Итоги игрового дня КХЛ\Материал\Лого НХЛ\Лого - НХЛ - Фон\Ванкувер.png",
#     "даллас": r"Z:\Documents\Hockey History\Telegram-канал\Графика\Итоги игрового дня КХЛ\Материал\Лого НХЛ\Лого - НХЛ - Фон\Даллас.png",
#     "далас": r"Z:\Documents\Hockey History\Telegram-канал\Графика\Итоги игрового дня КХЛ\Материал\Лого НХЛ\Лого - НХЛ - Фон\Даллас.png",
#     "детройт": r"Z:\Documents\Hockey History\Telegram-канал\Графика\Итоги игрового дня КХЛ\Материал\Лого НХЛ\Лого - НХЛ - Фон\Детройт.png",
#     "калгари": r"Z:\Documents\Hockey History\Telegram-канал\Графика\Итоги игрового дня КХЛ\Материал\Лого НХЛ\Лого - НХЛ - Фон\Калгари.png",
#     "коламбус": r"Z:\Documents\Hockey History\Telegram-канал\Графика\Итоги игрового дня КХЛ\Материал\Лого НХЛ\Лого - НХЛ - Фон\Коламбус.png",
#     "колорадо": r"Z:\Documents\Hockey History\Telegram-канал\Графика\Итоги игрового дня КХЛ\Материал\Лого НХЛ\Лого - НХЛ - Фон\Колорадо.png",
#     "каролина": r"Z:\Documents\Hockey History\Telegram-канал\Графика\Итоги игрового дня КХЛ\Материал\Лого НХЛ\Лого - НХЛ - Фон\Королина.png",
#     "вегас": r"Z:\Documents\Hockey History\Telegram-канал\Графика\Итоги игрового дня КХЛ\Материал\Лого НХЛ\Лого - НХЛ - Фон\Лас-Вегас.png",
#     "анджелес": r"Z:\Documents\Hockey History\Telegram-канал\Графика\Итоги игрового дня КХЛ\Материал\Лого НХЛ\Лого - НХЛ - Фон\Лос-Анджелес.png",
#     "лос-анджелес": r"Z:\Documents\Hockey History\Telegram-канал\Графика\Итоги игрового дня КХЛ\Материал\Лого НХЛ\Лого - НХЛ - Фон\Лос-Анджелес.png",
#     "миннисота": r"Z:\Documents\Hockey History\Telegram-канал\Графика\Итоги игрового дня КХЛ\Материал\Лого НХЛ\Лого - НХЛ - Фон\Минисота.png",
#     "минисота": r"Z:\Documents\Hockey History\Telegram-канал\Графика\Итоги игрового дня КХЛ\Материал\Лого НХЛ\Лого - НХЛ - Фон\Минисота.png",
#     "монреаль": r"Z:\Documents\Hockey History\Telegram-канал\Графика\Итоги игрового дня КХЛ\Материал\Лого НХЛ\Лого - НХЛ - Фон\Монреаль.png",
#     "нью-джерси": r"Z:\Documents\Hockey History\Telegram-канал\Графика\Итоги игрового дня КХЛ\Материал\Лого НХЛ\Лого - НХЛ - Фон\Нью-Джерси.png",
#     "джерси": r"Z:\Documents\Hockey History\Telegram-канал\Графика\Итоги игрового дня КХЛ\Материал\Лого НХЛ\Лого - НХЛ - Фон\Нью-Джерси.png",
#     "рейнджерс": r"Z:\Documents\Hockey History\Telegram-канал\Графика\Итоги игрового дня КХЛ\Материал\Лого НХЛ\Лого - НХЛ - Фон\Нью-Йорк.png",
#     "айлендерс": r"Z:\Documents\Hockey History\Telegram-канал\Графика\Итоги игрового дня КХЛ\Материал\Лого НХЛ\Лого - НХЛ - Фон\Нью-Йорк-Айл.png",
#     "нэшвил": r"Z:\Documents\Hockey History\Telegram-канал\Графика\Итоги игрового дня КХЛ\Материал\Лого НХЛ\Лого - НХЛ - Фон\Нэшвил.png",
#     "нэшвилл": r"Z:\Documents\Hockey History\Telegram-канал\Графика\Итоги игрового дня КХЛ\Материал\Лого НХЛ\Лого - НХЛ - Фон\Нэшвил.png",
#     "оттава": r"Z:\Documents\Hockey History\Telegram-канал\Графика\Итоги игрового дня КХЛ\Материал\Лого НХЛ\Лого - НХЛ - Фон\Оттава.png",
#     "питсбург": r"Z:\Documents\Hockey History\Telegram-канал\Графика\Итоги игрового дня КХЛ\Материал\Лого НХЛ\Лого - НХЛ - Фон\Питсбург.png",
#     "сан-хосе": r"Z:\Documents\Hockey History\Telegram-канал\Графика\Итоги игрового дня КХЛ\Материал\Лого НХЛ\Лого - НХЛ - Фон\Сан-Хосе.png",
#     "хосе": r"Z:\Documents\Hockey History\Telegram-канал\Графика\Итоги игрового дня КХЛ\Материал\Лого НХЛ\Лого - НХЛ - Фон\Сан-Хосе.png",
#     "сент-луис": r"Z:\Documents\Hockey History\Telegram-канал\Графика\Итоги игрового дня КХЛ\Материал\Лого НХЛ\Лого - НХЛ - Фон\Сент-Луис.png",
#     "луис": r"Z:\Documents\Hockey History\Telegram-канал\Графика\Итоги игрового дня КХЛ\Материал\Лого НХЛ\Лого - НХЛ - Фон\Сент-Луис.png",
#     "сиэтл": r"Z:\Documents\Hockey History\Telegram-канал\Графика\Итоги игрового дня КХЛ\Материал\Лого НХЛ\Лого - НХЛ - Фон\Сиэтл.png",
#     "тампа-бэй": r"Z:\Documents\Hockey History\Telegram-канал\Графика\Итоги игрового дня КХЛ\Материал\Лого НХЛ\Лого - НХЛ - Фон\Тампа-бэй.png",
#     "тампа": r"Z:\Documents\Hockey History\Telegram-канал\Графика\Итоги игрового дня КХЛ\Материал\Лого НХЛ\Лого - НХЛ - Фон\Тампа-бэй.png",
#     "торонто": r"Z:\Documents\Hockey History\Telegram-канал\Графика\Итоги игрового дня КХЛ\Материал\Лого НХЛ\Лого - НХЛ - Фон\Торонто.png",
#     "филадельфия": r"Z:\Documents\Hockey History\Telegram-канал\Графика\Итоги игрового дня КХЛ\Материал\Лого НХЛ\Лого - НХЛ - Фон\Филадельфия.png",
#     "флорида": r"Z:\Documents\Hockey History\Telegram-канал\Графика\Итоги игрового дня КХЛ\Материал\Лого НХЛ\Лого - НХЛ - Фон\Флорида.png",
#     "чикаго": r"Z:\Documents\Hockey History\Telegram-канал\Графика\Итоги игрового дня КХЛ\Материал\Лого НХЛ\Лого - НХЛ - Фон\Чикаго.png",
#     "эдмонтон": r"Z:\Documents\Hockey History\Telegram-канал\Графика\Итоги игрового дня КХЛ\Материал\Лого НХЛ\Лого - НХЛ - Фон\Эдмонтон.png"
# }

logos_nhl = {
    "анахайм": "Анахайм.png",
    "аризона": "Аризона.png",
    "баффоло": "Баффоло.png",
    "бафоло": "Баффоло.png",
    "баффало": "Баффоло.png",
    "бафало": "Баффоло.png",
    "бостон": "Бостон.png",
    "вашингтон": "Вашингтон.png",
    "виннипег": "Винипег.png",
    "винипег": "Винипег.png",
    "ванкувер": "Ванкувер.png",
    "даллас": "Даллас.png",
    "далас": "Даллас.png",
    "детройт": "Детройт.png",
    "калгари": "Калгари.png",
    "коламбус": "Коламбус.png",
    "колорадо": "Колорадо.png",
    "каролина": "Королина.png",
    "вегас": "Лас-Вегас.png",
    "анджелес": "Лос-Анджелес.png",
    "лос-анджелес": "Лос-Анджелес.png",
    "миннисота": "Минисота.png",
    "минисота": "Минисота.png",
    "монреаль": "Монреаль.png",
    "нью-джерси": "Нью-Джерси.png",
    "джерси": "Нью-Джерси.png",
    "рейнджерс": "Нью-Йорк.png",
    "айлендерс": "Нью-Йорк-Айл.png",
    "нэшвил": "Нэшвил.png",
    "нэшвилл": "Нэшвил.png",
    "оттава": "Оттава.png",
    "питсбург": "Питсбург.png",
    "сан-хосе": "Сан-Хосе.png",
    "хосе": "Сан-Хосе.png",
    "сент-луис": "Сент-Луис.png",
    "луис": "Сент-Луис.png",
    "сиэтл": "Сиэтл.png",
    "тампа-бэй": "Тампа-бэй.png",
    "тампа": "Тампа-бэй.png",
    "торонто": "Торонто.png",
    "филадельфия": "Филадельфия.png",
    "флорида": "Флорида.png",
    "чикаго": "Чикаго.png",
    "эдмонтон": "Эдмонтон.png"
}

# Фоны
name_template_khl = "pic_fone_khl.png"
name_template_nhl = "pic_fone_nhl.png"

# Путь к шрифту
name_font_path = "yearbooksolidcyr_regular.ttf"

